# Generated by Django 3.2.7 on 2021-09-20 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_active_list_bid_comments_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='aucation_item',
            new_name='auction_item',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='aucation_item',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='aucation_item',
        ),
        migrations.AddField(
            model_name='comments',
            name='auction_item',
            field=models.ManyToManyField(blank=True, related_name='auction', to='auctions.active_list'),
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction_item',
            field=models.ManyToManyField(blank=True, to='auctions.active_list'),
        ),
    ]
