# Generated by Django 3.2.7 on 2021-09-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_auction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='auction_id',
            field=models.IntegerField(default='0'),
        ),
    ]
