# Generated by Django 3.2.7 on 2021-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments_auction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_list',
            name='closed_auction',
            field=models.BooleanField(default='False'),
        ),
    ]
